version: '3.3'
services:
  redis:
    build: ./redis
    restart: always
    container_name: redis-container
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
      - REDIS_PASSWORD=YourStrongPasswordHere
    volumes:
      - ./.env:/usr/local/bin/.env
