server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      tracking-modes: COOKIE
      timeout: 30m
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/data.sql
        - classpath:db/schedule_data.sql
        - classpath:db/voucher_data.sql
        - classpath:db/reservation_data.sql
        - classpath:db/payment_data.sql
        - classpath:db/counsel_data.sql
        - classpath:db/review_data.sql
      schema-locations:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: true
    open-in-view: false



